### ISSUE TITLE
COPO API not retrieving data

### ISSUE THREAD

**Issue by sujaikumar** [DToL-Plant-Working-Group/collections#8]
Hi @Euphrasiologist

The automation/actions https://github.com/DToL-Plant-Working-Group/collections/actions ran fine till yesterday but failed yesterday. While debugging, I think the problem is happening during the `src/get_and_format_data.bash` script in this line:

```
curl https://copo-project.org/api/sample/dtol/ > ./sample_names.json
```
which is giving 0 results. Am assuming that's what is causing it to fail. Has this happened to you before? Should we ask COPO why their API isn't working?

**Comment by Euphrasiologist** [comment]
This looks to me to be a COPO problem; I had a look at the COPO API and it doesn't look as if anything has changed. It's possible that the problem is only temporary? 

Otherwise we'll have to contact the COPO people!

**Comment by Euphrasiologist** [comment]
I'm pretty sure this is working now, so I'm gonna close this :)
